// This file is auto-generated by scripts/generate-locales.cjs. Do not edit manually.
import ar_BMICalculator from './ar/BMICalculator.json';
import ar_CalorieBurner from './ar/CalorieBurner.json';
import ar_common from './ar/common.json';
import ar_DiabetesDiet from './ar/DiabetesDiet.json';
import ar_FoodDiary from './ar/FoodDiary.json';
import ar_IntermittentFasting from './ar/IntermittentFasting.json';
import ar_MacroCalculator from './ar/MacroCalculator.json';
import ar_MacroEducation from './ar/MacroEducation.json';
import ar_MuscleGain from './ar/MuscleGain.json';
import ar_StepTracker from './ar/StepTracker.json';
import ar_VeganNutrition from './ar/VeganNutrition.json';
import ar_WaterIntake from './ar/WaterIntake.json';
import ar_WeightLoss from './ar/WeightLoss.json';
import bn_common from './bn/common.json';
import bn_FoodDiary from './bn/FoodDiary.json';
import bn_IntermittentFasting from './bn/IntermittentFasting.json';
import bn_MuscleGain from './bn/MuscleGain.json';
import cs_common from './cs/common.json';
import cs_FoodDiary from './cs/FoodDiary.json';
import cs_IntermittentFasting from './cs/IntermittentFasting.json';
import cs_MuscleGain from './cs/MuscleGain.json';
import da_common from './da/common.json';
import da_FoodDiary from './da/FoodDiary.json';
import da_IntermittentFasting from './da/IntermittentFasting.json';
import da_MuscleGain from './da/MuscleGain.json';
import de_BMICalculator from './de/BMICalculator.json';
import de_CalorieBurner from './de/CalorieBurner.json';
import de_common from './de/common.json';
import de_DiabetesDiet from './de/DiabetesDiet.json';
import de_FoodDiary from './de/FoodDiary.json';
import de_IntermittentFasting from './de/IntermittentFasting.json';
import de_MacroCalculator from './de/MacroCalculator.json';
import de_MacroEducation from './de/MacroEducation.json';
import de_MuscleGain from './de/MuscleGain.json';
import de_StepTracker from './de/StepTracker.json';
import de_VeganNutrition from './de/VeganNutrition.json';
import de_WaterIntake from './de/WaterIntake.json';
import de_WeightLoss from './de/WeightLoss.json';
import el_common from './el/common.json';
import el_FoodDiary from './el/FoodDiary.json';
import el_IntermittentFasting from './el/IntermittentFasting.json';
import el_MuscleGain from './el/MuscleGain.json';
import en_BMICalculator from './en/BMICalculator.json';
import en_CalorieBurner from './en/CalorieBurner.json';
import en_common from './en/common.json';
import en_DiabetesDiet from './en/DiabetesDiet.json';
import en_FlexibilityMobility from './en/FlexibilityMobility.json';
import en_FoodDiary from './en/FoodDiary.json';
import en_GutHealth from './en/GutHealth.json';
import en_HeartHealth from './en/HeartHealth.json';
import en_IntermittentFasting from './en/IntermittentFasting.json';
import en_MacroCalculator from './en/MacroCalculator.json';
import en_MacroEducation from './en/MacroEducation.json';
import en_MuscleGain from './en/MuscleGain.json';
import en_StepTracker from './en/StepTracker.json';
import en_VeganNutrition from './en/VeganNutrition.json';
import en_WaterIntake from './en/WaterIntake.json';
import en_WeightLoss from './en/WeightLoss.json';
import es_BMICalculator from './es/BMICalculator.json';
import es_CalorieBurner from './es/CalorieBurner.json';
import es_common from './es/common.json';
import es_DiabetesDiet from './es/DiabetesDiet.json';
import es_FoodDiary from './es/FoodDiary.json';
import es_IntermittentFasting from './es/IntermittentFasting.json';
import es_MacroCalculator from './es/MacroCalculator.json';
import es_MacroEducation from './es/MacroEducation.json';
import es_MuscleGain from './es/MuscleGain.json';
import es_StepTracker from './es/StepTracker.json';
import es_VeganNutrition from './es/VeganNutrition.json';
import es_WaterIntake from './es/WaterIntake.json';
import es_WeightLoss from './es/WeightLoss.json';
import fi_common from './fi/common.json';
import fi_FoodDiary from './fi/FoodDiary.json';
import fi_IntermittentFasting from './fi/IntermittentFasting.json';
import fi_MuscleGain from './fi/MuscleGain.json';
import fr_BMICalculator from './fr/BMICalculator.json';
import fr_CalorieBurner from './fr/CalorieBurner.json';
import fr_common from './fr/common.json';
import fr_DiabetesDiet from './fr/DiabetesDiet.json';
import fr_FoodDiary from './fr/FoodDiary.json';
import fr_IntermittentFasting from './fr/IntermittentFasting.json';
import fr_MacroCalculator from './fr/MacroCalculator.json';
import fr_MacroEducation from './fr/MacroEducation.json';
import fr_MuscleGain from './fr/MuscleGain.json';
import fr_StepTracker from './fr/StepTracker.json';
import fr_VeganNutrition from './fr/VeganNutrition.json';
import fr_WaterIntake from './fr/WaterIntake.json';
import fr_WeightLoss from './fr/WeightLoss.json';
import he_common from './he/common.json';
import he_FoodDiary from './he/FoodDiary.json';
import he_IntermittentFasting from './he/IntermittentFasting.json';
import he_MuscleGain from './he/MuscleGain.json';
import hi_BMICalculator from './hi/BMICalculator.json';
import hi_CalorieBurner from './hi/CalorieBurner.json';
import hi_common from './hi/common.json';
import hi_DiabetesDiet from './hi/DiabetesDiet.json';
import hi_FoodDiary from './hi/FoodDiary.json';
import hi_IntermittentFasting from './hi/IntermittentFasting.json';
import hi_MacroCalculator from './hi/MacroCalculator.json';
import hi_MacroEducation from './hi/MacroEducation.json';
import hi_MuscleGain from './hi/MuscleGain.json';
import hi_StepTracker from './hi/StepTracker.json';
import hi_VeganNutrition from './hi/VeganNutrition.json';
import hi_WaterIntake from './hi/WaterIntake.json';
import hi_WeightLoss from './hi/WeightLoss.json';
import hu_common from './hu/common.json';
import hu_FoodDiary from './hu/FoodDiary.json';
import hu_IntermittentFasting from './hu/IntermittentFasting.json';
import hu_MuscleGain from './hu/MuscleGain.json';
import id_common from './id/common.json';
import id_FoodDiary from './id/FoodDiary.json';
import id_IntermittentFasting from './id/IntermittentFasting.json';
import id_MuscleGain from './id/MuscleGain.json';
import it_BMICalculator from './it/BMICalculator.json';
import it_CalorieBurner from './it/CalorieBurner.json';
import it_common from './it/common.json';
import it_DiabetesDiet from './it/DiabetesDiet.json';
import it_FoodDiary from './it/FoodDiary.json';
import it_IntermittentFasting from './it/IntermittentFasting.json';
import it_MacroCalculator from './it/MacroCalculator.json';
import it_MacroEducation from './it/MacroEducation.json';
import it_MuscleGain from './it/MuscleGain.json';
import it_StepTracker from './it/StepTracker.json';
import it_VeganNutrition from './it/VeganNutrition.json';
import it_WaterIntake from './it/WaterIntake.json';
import it_WeightLoss from './it/WeightLoss.json';
import ja_BMICalculator from './ja/BMICalculator.json';
import ja_CalorieBurner from './ja/CalorieBurner.json';
import ja_common from './ja/common.json';
import ja_DiabetesDiet from './ja/DiabetesDiet.json';
import ja_FoodDiary from './ja/FoodDiary.json';
import ja_IntermittentFasting from './ja/IntermittentFasting.json';
import ja_MacroCalculator from './ja/MacroCalculator.json';
import ja_MacroEducation from './ja/MacroEducation.json';
import ja_MuscleGain from './ja/MuscleGain.json';
import ja_StepTracker from './ja/StepTracker.json';
import ja_VeganNutrition from './ja/VeganNutrition.json';
import ja_WaterIntake from './ja/WaterIntake.json';
import ja_WeightLoss from './ja/WeightLoss.json';
import ko_BMICalculator from './ko/BMICalculator.json';
import ko_CalorieBurner from './ko/CalorieBurner.json';
import ko_common from './ko/common.json';
import ko_DiabetesDiet from './ko/DiabetesDiet.json';
import ko_FlexibilityMobility from './ko/FlexibilityMobility.json';
import ko_FoodDiary from './ko/FoodDiary.json';
import ko_GutHealth from './ko/GutHealth.json';
import ko_HeartHealth from './ko/HeartHealth.json';
import ko_IntermittentFasting from './ko/IntermittentFasting.json';
import ko_MacroCalculator from './ko/MacroCalculator.json';
import ko_MacroEducation from './ko/MacroEducation.json';
import ko_MuscleGain from './ko/MuscleGain.json';
import ko_StepTracker from './ko/StepTracker.json';
import ko_VeganNutrition from './ko/VeganNutrition.json';
import ko_WaterIntake from './ko/WaterIntake.json';
import ko_WeightLoss from './ko/WeightLoss.json';
import ms_common from './ms/common.json';
import ms_FoodDiary from './ms/FoodDiary.json';
import ms_IntermittentFasting from './ms/IntermittentFasting.json';
import ms_MuscleGain from './ms/MuscleGain.json';
import nl_BMICalculator from './nl/BMICalculator.json';
import nl_common from './nl/common.json';
import nl_FoodDiary from './nl/FoodDiary.json';
import nl_IntermittentFasting from './nl/IntermittentFasting.json';
import nl_MuscleGain from './nl/MuscleGain.json';
import no_common from './no/common.json';
import no_FoodDiary from './no/FoodDiary.json';
import no_IntermittentFasting from './no/IntermittentFasting.json';
import no_MuscleGain from './no/MuscleGain.json';
import pl_BMICalculator from './pl/BMICalculator.json';
import pl_common from './pl/common.json';
import pl_FoodDiary from './pl/FoodDiary.json';
import pl_IntermittentFasting from './pl/IntermittentFasting.json';
import pl_MuscleGain from './pl/MuscleGain.json';
import pt_BMICalculator from './pt/BMICalculator.json';
import pt_CalorieBurner from './pt/CalorieBurner.json';
import pt_common from './pt/common.json';
import pt_DiabetesDiet from './pt/DiabetesDiet.json';
import pt_FoodDiary from './pt/FoodDiary.json';
import pt_IntermittentFasting from './pt/IntermittentFasting.json';
import pt_MacroCalculator from './pt/MacroCalculator.json';
import pt_MacroEducation from './pt/MacroEducation.json';
import pt_MuscleGain from './pt/MuscleGain.json';
import pt_StepTracker from './pt/StepTracker.json';
import pt_VeganNutrition from './pt/VeganNutrition.json';
import pt_WaterIntake from './pt/WaterIntake.json';
import pt_WeightLoss from './pt/WeightLoss.json';
import ro_common from './ro/common.json';
import ro_FoodDiary from './ro/FoodDiary.json';
import ro_IntermittentFasting from './ro/IntermittentFasting.json';
import ro_MuscleGain from './ro/MuscleGain.json';
import ru_BMICalculator from './ru/BMICalculator.json';
import ru_CalorieBurner from './ru/CalorieBurner.json';
import ru_common from './ru/common.json';
import ru_DiabetesDiet from './ru/DiabetesDiet.json';
import ru_FoodDiary from './ru/FoodDiary.json';
import ru_IntermittentFasting from './ru/IntermittentFasting.json';
import ru_MacroCalculator from './ru/MacroCalculator.json';
import ru_MacroEducation from './ru/MacroEducation.json';
import ru_MuscleGain from './ru/MuscleGain.json';
import ru_StepTracker from './ru/StepTracker.json';
import ru_VeganNutrition from './ru/VeganNutrition.json';
import ru_WaterIntake from './ru/WaterIntake.json';
import ru_WeightLoss from './ru/WeightLoss.json';
import sv_common from './sv/common.json';
import sv_FoodDiary from './sv/FoodDiary.json';
import sv_IntermittentFasting from './sv/IntermittentFasting.json';
import sv_MuscleGain from './sv/MuscleGain.json';
import ta_common from './ta/common.json';
import ta_FoodDiary from './ta/FoodDiary.json';
import ta_IntermittentFasting from './ta/IntermittentFasting.json';
import ta_MuscleGain from './ta/MuscleGain.json';
import te_common from './te/common.json';
import te_FoodDiary from './te/FoodDiary.json';
import te_IntermittentFasting from './te/IntermittentFasting.json';
import te_MuscleGain from './te/MuscleGain.json';
import th_common from './th/common.json';
import th_FoodDiary from './th/FoodDiary.json';
import th_IntermittentFasting from './th/IntermittentFasting.json';
import th_MuscleGain from './th/MuscleGain.json';
import tl_common from './tl/common.json';
import tl_FoodDiary from './tl/FoodDiary.json';
import tl_IntermittentFasting from './tl/IntermittentFasting.json';
import tl_MuscleGain from './tl/MuscleGain.json';
import tr_common from './tr/common.json';
import tr_FoodDiary from './tr/FoodDiary.json';
import tr_IntermittentFasting from './tr/IntermittentFasting.json';
import tr_MuscleGain from './tr/MuscleGain.json';
import uk_common from './uk/common.json';
import uk_FoodDiary from './uk/FoodDiary.json';
import uk_IntermittentFasting from './uk/IntermittentFasting.json';
import uk_MuscleGain from './uk/MuscleGain.json';
import ur_common from './ur/common.json';
import ur_FoodDiary from './ur/FoodDiary.json';
import ur_IntermittentFasting from './ur/IntermittentFasting.json';
import ur_MuscleGain from './ur/MuscleGain.json';
import vi_common from './vi/common.json';
import vi_FoodDiary from './vi/FoodDiary.json';
import vi_IntermittentFasting from './vi/IntermittentFasting.json';
import vi_MuscleGain from './vi/MuscleGain.json';
import zh_Hans_common from './zh-Hans/common.json';
import zh_Hans_FoodDiary from './zh-Hans/FoodDiary.json';
import zh_Hans_IntermittentFasting from './zh-Hans/IntermittentFasting.json';
import zh_Hans_MuscleGain from './zh-Hans/MuscleGain.json';
import zh_Hant_common from './zh-Hant/common.json';
import zh_Hant_FoodDiary from './zh-Hant/FoodDiary.json';
import zh_Hant_IntermittentFasting from './zh-Hant/IntermittentFasting.json';
import zh_Hant_MuscleGain from './zh-Hant/MuscleGain.json';

export const resources: any = {
  'ar': {
    'BMICalculator': ar_BMICalculator,
    'CalorieBurner': ar_CalorieBurner,
    'common': ar_common,
    'DiabetesDiet': ar_DiabetesDiet,
    'FoodDiary': ar_FoodDiary,
    'IntermittentFasting': ar_IntermittentFasting,
    'MacroCalculator': ar_MacroCalculator,
    'MacroEducation': ar_MacroEducation,
    'MuscleGain': ar_MuscleGain,
    'StepTracker': ar_StepTracker,
    'VeganNutrition': ar_VeganNutrition,
    'WaterIntake': ar_WaterIntake,
    'WeightLoss': ar_WeightLoss,
  },
  'bn': {
    'common': bn_common,
    'FoodDiary': bn_FoodDiary,
    'IntermittentFasting': bn_IntermittentFasting,
    'MuscleGain': bn_MuscleGain,
  },
  'cs': {
    'common': cs_common,
    'FoodDiary': cs_FoodDiary,
    'IntermittentFasting': cs_IntermittentFasting,
    'MuscleGain': cs_MuscleGain,
  },
  'da': {
    'common': da_common,
    'FoodDiary': da_FoodDiary,
    'IntermittentFasting': da_IntermittentFasting,
    'MuscleGain': da_MuscleGain,
  },
  'de': {
    'BMICalculator': de_BMICalculator,
    'CalorieBurner': de_CalorieBurner,
    'common': de_common,
    'DiabetesDiet': de_DiabetesDiet,
    'FoodDiary': de_FoodDiary,
    'IntermittentFasting': de_IntermittentFasting,
    'MacroCalculator': de_MacroCalculator,
    'MacroEducation': de_MacroEducation,
    'MuscleGain': de_MuscleGain,
    'StepTracker': de_StepTracker,
    'VeganNutrition': de_VeganNutrition,
    'WaterIntake': de_WaterIntake,
    'WeightLoss': de_WeightLoss,
  },
  'el': {
    'common': el_common,
    'FoodDiary': el_FoodDiary,
    'IntermittentFasting': el_IntermittentFasting,
    'MuscleGain': el_MuscleGain,
  },
  'en': {
    'BMICalculator': en_BMICalculator,
    'CalorieBurner': en_CalorieBurner,
    'common': en_common,
    'DiabetesDiet': en_DiabetesDiet,
    'FlexibilityMobility': en_FlexibilityMobility,
    'FoodDiary': en_FoodDiary,
    'GutHealth': en_GutHealth,
    'HeartHealth': en_HeartHealth,
    'IntermittentFasting': en_IntermittentFasting,
    'MacroCalculator': en_MacroCalculator,
    'MacroEducation': en_MacroEducation,
    'MuscleGain': en_MuscleGain,
    'StepTracker': en_StepTracker,
    'VeganNutrition': en_VeganNutrition,
    'WaterIntake': en_WaterIntake,
    'WeightLoss': en_WeightLoss,
  },
  'es': {
    'BMICalculator': es_BMICalculator,
    'CalorieBurner': es_CalorieBurner,
    'common': es_common,
    'DiabetesDiet': es_DiabetesDiet,
    'FoodDiary': es_FoodDiary,
    'IntermittentFasting': es_IntermittentFasting,
    'MacroCalculator': es_MacroCalculator,
    'MacroEducation': es_MacroEducation,
    'MuscleGain': es_MuscleGain,
    'StepTracker': es_StepTracker,
    'VeganNutrition': es_VeganNutrition,
    'WaterIntake': es_WaterIntake,
    'WeightLoss': es_WeightLoss,
  },
  'fi': {
    'common': fi_common,
    'FoodDiary': fi_FoodDiary,
    'IntermittentFasting': fi_IntermittentFasting,
    'MuscleGain': fi_MuscleGain,
  },
  'fr': {
    'BMICalculator': fr_BMICalculator,
    'CalorieBurner': fr_CalorieBurner,
    'common': fr_common,
    'DiabetesDiet': fr_DiabetesDiet,
    'FoodDiary': fr_FoodDiary,
    'IntermittentFasting': fr_IntermittentFasting,
    'MacroCalculator': fr_MacroCalculator,
    'MacroEducation': fr_MacroEducation,
    'MuscleGain': fr_MuscleGain,
    'StepTracker': fr_StepTracker,
    'VeganNutrition': fr_VeganNutrition,
    'WaterIntake': fr_WaterIntake,
    'WeightLoss': fr_WeightLoss,
  },
  'he': {
    'common': he_common,
    'FoodDiary': he_FoodDiary,
    'IntermittentFasting': he_IntermittentFasting,
    'MuscleGain': he_MuscleGain,
  },
  'hi': {
    'BMICalculator': hi_BMICalculator,
    'CalorieBurner': hi_CalorieBurner,
    'common': hi_common,
    'DiabetesDiet': hi_DiabetesDiet,
    'FoodDiary': hi_FoodDiary,
    'IntermittentFasting': hi_IntermittentFasting,
    'MacroCalculator': hi_MacroCalculator,
    'MacroEducation': hi_MacroEducation,
    'MuscleGain': hi_MuscleGain,
    'StepTracker': hi_StepTracker,
    'VeganNutrition': hi_VeganNutrition,
    'WaterIntake': hi_WaterIntake,
    'WeightLoss': hi_WeightLoss,
  },
  'hu': {
    'common': hu_common,
    'FoodDiary': hu_FoodDiary,
    'IntermittentFasting': hu_IntermittentFasting,
    'MuscleGain': hu_MuscleGain,
  },
  'id': {
    'common': id_common,
    'FoodDiary': id_FoodDiary,
    'IntermittentFasting': id_IntermittentFasting,
    'MuscleGain': id_MuscleGain,
  },
  'it': {
    'BMICalculator': it_BMICalculator,
    'CalorieBurner': it_CalorieBurner,
    'common': it_common,
    'DiabetesDiet': it_DiabetesDiet,
    'FoodDiary': it_FoodDiary,
    'IntermittentFasting': it_IntermittentFasting,
    'MacroCalculator': it_MacroCalculator,
    'MacroEducation': it_MacroEducation,
    'MuscleGain': it_MuscleGain,
    'StepTracker': it_StepTracker,
    'VeganNutrition': it_VeganNutrition,
    'WaterIntake': it_WaterIntake,
    'WeightLoss': it_WeightLoss,
  },
  'ja': {
    'BMICalculator': ja_BMICalculator,
    'CalorieBurner': ja_CalorieBurner,
    'common': ja_common,
    'DiabetesDiet': ja_DiabetesDiet,
    'FoodDiary': ja_FoodDiary,
    'IntermittentFasting': ja_IntermittentFasting,
    'MacroCalculator': ja_MacroCalculator,
    'MacroEducation': ja_MacroEducation,
    'MuscleGain': ja_MuscleGain,
    'StepTracker': ja_StepTracker,
    'VeganNutrition': ja_VeganNutrition,
    'WaterIntake': ja_WaterIntake,
    'WeightLoss': ja_WeightLoss,
  },
  'ko': {
    'BMICalculator': ko_BMICalculator,
    'CalorieBurner': ko_CalorieBurner,
    'common': ko_common,
    'DiabetesDiet': ko_DiabetesDiet,
    'FlexibilityMobility': ko_FlexibilityMobility,
    'FoodDiary': ko_FoodDiary,
    'GutHealth': ko_GutHealth,
    'HeartHealth': ko_HeartHealth,
    'IntermittentFasting': ko_IntermittentFasting,
    'MacroCalculator': ko_MacroCalculator,
    'MacroEducation': ko_MacroEducation,
    'MuscleGain': ko_MuscleGain,
    'StepTracker': ko_StepTracker,
    'VeganNutrition': ko_VeganNutrition,
    'WaterIntake': ko_WaterIntake,
    'WeightLoss': ko_WeightLoss,
  },
  'ms': {
    'common': ms_common,
    'FoodDiary': ms_FoodDiary,
    'IntermittentFasting': ms_IntermittentFasting,
    'MuscleGain': ms_MuscleGain,
  },
  'nl': {
    'BMICalculator': nl_BMICalculator,
    'common': nl_common,
    'FoodDiary': nl_FoodDiary,
    'IntermittentFasting': nl_IntermittentFasting,
    'MuscleGain': nl_MuscleGain,
  },
  'no': {
    'common': no_common,
    'FoodDiary': no_FoodDiary,
    'IntermittentFasting': no_IntermittentFasting,
    'MuscleGain': no_MuscleGain,
  },
  'pl': {
    'BMICalculator': pl_BMICalculator,
    'common': pl_common,
    'FoodDiary': pl_FoodDiary,
    'IntermittentFasting': pl_IntermittentFasting,
    'MuscleGain': pl_MuscleGain,
  },
  'pt': {
    'BMICalculator': pt_BMICalculator,
    'CalorieBurner': pt_CalorieBurner,
    'common': pt_common,
    'DiabetesDiet': pt_DiabetesDiet,
    'FoodDiary': pt_FoodDiary,
    'IntermittentFasting': pt_IntermittentFasting,
    'MacroCalculator': pt_MacroCalculator,
    'MacroEducation': pt_MacroEducation,
    'MuscleGain': pt_MuscleGain,
    'StepTracker': pt_StepTracker,
    'VeganNutrition': pt_VeganNutrition,
    'WaterIntake': pt_WaterIntake,
    'WeightLoss': pt_WeightLoss,
  },
  'ro': {
    'common': ro_common,
    'FoodDiary': ro_FoodDiary,
    'IntermittentFasting': ro_IntermittentFasting,
    'MuscleGain': ro_MuscleGain,
  },
  'ru': {
    'BMICalculator': ru_BMICalculator,
    'CalorieBurner': ru_CalorieBurner,
    'common': ru_common,
    'DiabetesDiet': ru_DiabetesDiet,
    'FoodDiary': ru_FoodDiary,
    'IntermittentFasting': ru_IntermittentFasting,
    'MacroCalculator': ru_MacroCalculator,
    'MacroEducation': ru_MacroEducation,
    'MuscleGain': ru_MuscleGain,
    'StepTracker': ru_StepTracker,
    'VeganNutrition': ru_VeganNutrition,
    'WaterIntake': ru_WaterIntake,
    'WeightLoss': ru_WeightLoss,
  },
  'sv': {
    'common': sv_common,
    'FoodDiary': sv_FoodDiary,
    'IntermittentFasting': sv_IntermittentFasting,
    'MuscleGain': sv_MuscleGain,
  },
  'ta': {
    'common': ta_common,
    'FoodDiary': ta_FoodDiary,
    'IntermittentFasting': ta_IntermittentFasting,
    'MuscleGain': ta_MuscleGain,
  },
  'te': {
    'common': te_common,
    'FoodDiary': te_FoodDiary,
    'IntermittentFasting': te_IntermittentFasting,
    'MuscleGain': te_MuscleGain,
  },
  'th': {
    'common': th_common,
    'FoodDiary': th_FoodDiary,
    'IntermittentFasting': th_IntermittentFasting,
    'MuscleGain': th_MuscleGain,
  },
  'tl': {
    'common': tl_common,
    'FoodDiary': tl_FoodDiary,
    'IntermittentFasting': tl_IntermittentFasting,
    'MuscleGain': tl_MuscleGain,
  },
  'tr': {
    'common': tr_common,
    'FoodDiary': tr_FoodDiary,
    'IntermittentFasting': tr_IntermittentFasting,
    'MuscleGain': tr_MuscleGain,
  },
  'uk': {
    'common': uk_common,
    'FoodDiary': uk_FoodDiary,
    'IntermittentFasting': uk_IntermittentFasting,
    'MuscleGain': uk_MuscleGain,
  },
  'ur': {
    'common': ur_common,
    'FoodDiary': ur_FoodDiary,
    'IntermittentFasting': ur_IntermittentFasting,
    'MuscleGain': ur_MuscleGain,
  },
  'vi': {
    'common': vi_common,
    'FoodDiary': vi_FoodDiary,
    'IntermittentFasting': vi_IntermittentFasting,
    'MuscleGain': vi_MuscleGain,
  },
  'zh-Hans': {
    'common': zh_Hans_common,
    'FoodDiary': zh_Hans_FoodDiary,
    'IntermittentFasting': zh_Hans_IntermittentFasting,
    'MuscleGain': zh_Hans_MuscleGain,
  },
  'zh-Hant': {
    'common': zh_Hant_common,
    'FoodDiary': zh_Hant_FoodDiary,
    'IntermittentFasting': zh_Hant_IntermittentFasting,
    'MuscleGain': zh_Hant_MuscleGain,
  },
};

